module HTTP
  class MozillaCookieJar < FileCookieJar
    HEADER = "# Netscape HTTP Cookie File\n" \
             "# https://curl.se/docs/http-cookies.html\n" \
             "# This file was generated by cookiejar."

    protected def write(io : IO, include_session : Bool = false) : Nil
      io << HEADER
      io << '\n'

      each do |entry|
        next if !include_session && !entry.persistent

        io << serialize_entry(entry)
        io << '\n'
      end
    end

    protected def read(io : IO) : Nil
      io.each_line do |line|
        line = line.strip
        next if line.empty?
        next if comment?(line) && !http_only_comment?(line)

        if entry = parse_entry(line)
          add_entry(entry) unless entry.expired?
        end
      end
    end

    private def serialize_entry(entry : Entry) : String
      domain = entry.host_only ? entry.domain : ".#{entry.domain}"
      domain = "#HttpOnly_#{domain}" if entry.http_only

      [
        domain,
        (!entry.host_only).to_s.upcase,
        entry.path,
        entry.secure.to_s.upcase,
        serialize_expires(entry),
        entry.name,
        entry.value,
      ].join('\t')
    end

    private def serialize_expires(entry : Entry) : String
      entry.expires_at ? entry.expires_at.not_nil!.to_unix.to_s : "0"
    end

    private def parse_entry(line : String) : Entry?
      http_only = false

      if line.starts_with?("#HttpOnly_")
        http_only = true
        line = line.lchop("#HttpOnly_")
      end

      parts = line.split('\t')
      return unless parts.size == 7

      domain = parts[0].lstrip('.').downcase
      host_only = parts[1] != "TRUE"
      path = parts[2]
      secure = parts[3] == "TRUE"
      expires_at = parse_expires(parts[4])
      name = parts[5]
      value = parts[6]

      cookie = HTTP::Cookie.new(
        name,
        value,
        path: path,
        expires: expires_at,
        domain: host_only ? nil : domain,
        secure: secure,
        http_only: http_only
      )

      Entry.new(
        cookie: cookie,
        domain: domain,
        path: path,
        expires_at: expires_at,
        host_only: host_only,
        persistent: parts[4] != "0"
      )
    rescue
      nil
    end

    private def parse_expires(raw : String) : Time?
      return if raw == "0"

      Time.unix(raw.to_i64)
    end

    private def comment?(line : String) : Bool
      line.starts_with?('#')
    end

    private def http_only_comment?(line : String) : Bool
      line.starts_with?("#HttpOnly_")
    end
  end
end
